export const COLORS: any = {
  white: 'white',
  black: 'black',
  silver: 'silver',
  gray: 'grey',
  red: 'red',
  green: 'green',
  blue: 'blue',
  beige: 'beige',
  brown: 'brown',
  gold: 'gold',
  yellow: 'yellow',
  orange: 'orange',
  purple: 'purple',
  whiteBlack: 'linear-gradient(45deg, #fff 47%, #000 53%)',
  silverRed: 'linear-gradient(45deg, #ccc 47%, #f44336 53%)',
  whiteBlue: 'linear-gradient(45deg, #fff 47%, #1e90ff 53%)',
  other: 'linear-gradient(to right, #d9afd9 0%, #97d9e1 100%)',
};
